export const FETCH_LINK_FOR_PERMALINK = 'FETCH_LINK_FOR_PERMALINK';
export const EDIT_GUTENBERG_LINK = 'EDIT_GUTENBERG_LINK';
export const EDIT_LINK_EXPIRE_OPTION = 'EDIT_LINK_EXPIRE_OPTION';
export const DELETE_GUTENBERG_LINK = 'DELETE_GUTENBERG_LINK';
export const RESET_GUTENBERG_INSTANT_REDIRECT = 'RESET_GUTENBERG_INSTANT_REDIRECT';
