export const FETCH_LINK_FOR_PERMALINK = 'FETCH_LINK_FOR_PERMALINK';
export const EDIT_GUTENBERG_LINK = 'EDIT_GUTENBERG_LINK';
export const EDIT_LINK_EXPIRE_OPTION = 'EDIT_LINK_EXPIRE_OPTION';
export const DELETE_GUTENBERG_LINK = 'DELETE_GUTENBERG_LINK';
export const RESET_GUTENBERG_INSTANT_REDIRECT = 'RESET_GUTENBERG_INSTANT_REDIRECT';
export const FETCH_TERMS_DATA = 'FETCH_TERMS_DATA';
export const ADD_TERM = 'ADD_TERM';
export const UPDATE_TERM = 'UPDATE_TERM';
export const DELETE_TERM = 'DELETE_TERM';
export const FETCH_TAGS = 'FETCH_TAGS';

export const FETCH_LINK_BY_PERMALINK = 'FETCH_LINK_BY_PERMALINK';
export const SAVE_GUTENBERG_AUTO_LINK = 'SAVE_GUTENBERG_AUTO_LINK';
export const EDIT_GUTENBERG_AUTO_LINK = 'EDIT_GUTENBERG_AUTO_LINK';

export const FETCH_AUTO_LINK_DISABLE_IDS = 'FETCH_AUTO_LINK_DISABLE_IDS';

// Affiliate disclosure
export const SAVE_GUTENBERG_AFFILIATE_DISCLOSURE = 'SAVE_GUTENBERG_AFFILIATE_DISCLOSURE';
export const EDIT_GUTENBERG_AFFILIATE_DISCLOSURE = 'EDIT_GUTENBERG_AFFILIATE_DISCLOSURE';
export const FETCH_AUTOLINK_SETTINGS = 'FETCH_AUTOLINK_SETTINGS';

// Password Protection
export const ADD_NEW_PASSWORD = 'ADD_NEW_PASSWORD';
export const REMOVE_PASSWORD = 'REMOVE_PASSWWORD';
export const EDIT_PASSWORD = 'EDIT_PASSWORD';
export const FETCH_LINKS_PASSWORD = 'FETCH_LINKS_PASSWORD';

// Analytics
export const FETCH_ANALYTICS_SETTINGS = 'FETCH_ANALYTICS_SETTINGS';
export const UPDATE_ANALYTICS_SETTINGS = 'UPDATE_ANALYTICS_SETTINGS';
